version: '3.7'

services:
  file-server:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PORT: ${CONTAINER_PORT}
    image: file-server
    container_name: file-server
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1g"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://172.17.0.1:8080/api/file-server/v1/health" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
    ports:
      - 8081:${CONTAINER_PORT}
    volumes:
      - ${HOST_DATA_DIR}:${ENV_STORAGE_PATH}
      - ${HOST_DATA_DIR}/file-server-jar/logs:/.logs
