version: '3.7'

services:
  file-server:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PORT: 80
        PROFILE: dev
    image: file-server
    container_name: file-server
    restart: always
    environment:
      ENV_STORAGE_PATH: "${ENV_STORAGE_PATH}"
      PROFILE: "${PROFILE}"
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
      PORT: "${CONTAINER_PORT}"

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://172.17.0.1:8080/api/file-server/v1/health" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
    ports:
      - "127.0.0.1:${ROOT_PORT}:80"
      - "172.17.0.1:${ROOT_PORT}:80"
    volumes:
      - ${HOST_DATA_DIR}:/root/.storage/
      - /opt/:/opt/
