server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/file-server/v1/

spring:
  main:
    web-application-type: servlet

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 1024MB
      max-request-size: 1024MB

